### ISSUE TITLE
GSL QRNG auto-generated binding accepts a double instead of pointer-to-double

### ISSUE THREAD

**Issue by ikirill** [jiahao/GSL.jl#24]
Here: https://github.com/jiahao/GSL.jl/blob/master/src/_19_2_Sampling_from_a_quasi-random_number_generator.jl#L16

Compare: http://www.gnu.org/software/gsl/manual/html_node/Sampling-from-a-quasi_002drandom-number-generator.html#Sampling-from-a-quasi_002drandom-number-generator

**Comment by jiahao** [comment]
Thanks for the report. There is indeed an error in the wrapper.
