### ISSUE TITLE
Function arrays not working

### ISSUE THREAD

**Issue by johnwormell** [jiahao/GSL.jl#35]
Hi,

In `sf_legendre_Pl_array` and perhaps similar functions, Julia raises the following error on a variety of inputs (on a Mac at least):
```
`convert` has no method matching convert(::Type{Float64},::Array{Float64,1})
in sf_legendre_Pl_array at _7_24_1_Legendre_Polynomials.jl:116
```

Not really sure what's going on here as I'm not familiar with C/ccall at all, but hope that helps.

**Comment by jiahao** [comment]
Thank you for the report. It turns out that I did not generate the wrapper correctly.

**Comment by pochoi** [comment]
Maybe other related functions, such as `sf_legendre_Plm_array` also suffers from the same problem?

```
julia> sf_legendre_Plm_array(10,2, 0)
ERROR: MethodError: `convert` has no method matching convert(::Type{Float64}, ::Base.RefValue{Float64})
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
```

**Comment by jiahao** [comment]
Yes it's quite likely. I generated these wrappers using some heuristics and it's simply not possible for me to manually check them all.

I would be more than happy to review a PR if you would like to submit a fix similar to what I did for this issue.

**Comment by pochoi** [comment]
#46 
Thanks!
