### ISSUE TITLE
Multiroot not working / v0.4?

### ISSUE THREAD

**Issue by laurentbartholdi** [jiahao/GSL.jl#36]
Dear Jiahao:
I tried to test the gsl multiroot finding code, but failed. Using v0.3.11, I tried the test file examples/35_Multidimensional_Root_Finding.jl and it gives the error message
ERROR: Ref not defined
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/laurent/test.jl, in expression starting on line 34

I also tried GSL with v0.4, and there the package GSL shows lots of warnings upon loading; and then
ERROR: LoadError: MethodError: `multiroot_fsolver_iterate` has no method matching multiroot_fsolver_iterate(::Ptr{GSL.gsl_multiroot_fsolver})
 in anonymous at no file:57
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267

Thanks in advance! Laurent

**Comment by jiahao** [comment]
Thanks for the report. Wrapping the more advanced GSL functions has proven challenging because of the large number of custom C structs that are used in GSL and I don't think they have every worked. The main issue is my lack of time to verify the wrappers.

**Comment by jiahao** [comment]
Presumed fixed by #40
