### ISSUE TITLE
Got exception when calling julia from c++

### ISSUE THREAD

**Issue by Jasonqian1** [jiahao/GSL.jl#56]
Hi ,

  I have a java test program that calling C++ (JNI) and the C++ calling Julia.
  It works fine when running one instance, but when repeatedly running the instance, I got following 
  error (In our real application, it killed the running processor).

  Julia 0.4.6 : julia-0.4.6-linux-x86_64
  Linux : 2.6.32-358.el6.x86_64
  gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC)

Thanks
Jason

fatal: error thrown and no exception handler available.
ReadOnlyMemoryError()
rec_backtrace at /home/Julia/julia-2e358ce975/lib/julia/libjulia.so (unknown line)
jl_throw at /home/Julia/julia-2e358ce975/lib/julia/libjulia.so (unknown line)
jl_exit_on_sigint at /home/Julia/julia-2e358ce975/lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x3e8a40f500)
unknown function (ip: 0x7f9244ddf1e4)
unknown function (ip: 0x7f9244dd8365)
unknown function (ip: 0x7f9244f1992f)
unknown function (ip: 0x7f9244f19a35)
unknown function (ip: 0x7f9244de04b8)
unknown function (ip: 0x3e8a407851)
clone at /lib64/libc.so.6 (unknown line)
unknown function (ip: (nil))

**Comment by jiahao** [comment]
There is not enough information to diagnose what happened. All we can tell at the moment is that `ReadOnlyMemoryError()` signals some sort of memory error, possibly out of memory or invalid access.

What is the source code of your test program? What is your test program doing? Have you tried linking against a debug build of the library (which would get you a better stack trace)? Which GSL functions did you call from Julia? Which version of the GSL library are you using?

**Comment by AndyGreenwell** [comment]
This issue was solved [here](https://github.com/JuliaLang/julia/issues/17767).  The issue was with handling signals when called from code via the JNI.
